
rooms = [
    {
        '_id': '1',
        'name': 'Chloe',
        'image': '/images/chloe.jpg',
        'price': '15,000',
        'location': 'Japan',
        'description': 'Experience the beauty of Japan, with a warm and inviting atmosphere. Our spacious rooms are perfect for relaxation and relaxation. Book your stay today!',
        'rating': 5,
    },
    {
        '_id': '2',
        'name': 'Franco',
        'image': '/images/franco.jpg',
        'price': '13,000',
        'location': 'Bahamas',
        'description': 'Relax in a stylish, cozy retreat featuring modern amenities, breathtaking views, and a prime location near Miami Your perfect getaway awaits!',
        'rating': 4,
    },
    {
        '_id': '3',
        'name': 'Simon',
        'image': '/images/simon.jpg',
        'price': '15,000',
        'location': 'Angeles',
        'description': 'Experience the beauty of Angeles, with a warm and inviting atmosphere. Our spacious rooms are perfect for relaxation and relaxation. Book your stay today!',
        'rating': 3.5,
    },
    {
        '_id': '4',
        'name': 'Miguel',
        'image': '/images/miguel.jpg',
        'price': '17,000',
        'location': 'Tondo',
        'description': 'Unwind in our serene Airbnb, offering plush bedding, free Wi-Fi, and a peaceful atmosphere just minutes from Manila.',
        'rating': 3,
    },
    {
        '_id': '5',
        'name': 'Monica',
        'image': '/images/monica.jpg',
        'price': '20,000',
        'location': 'Boracay',
        'description': 'Experience comfort and convenience in our beautifully designed space, complete with a fully equipped kitchen and easy access to parks and vibrant nightlife. Book your stay today!',
        'rating': 2,
    },
    {
        '_id': '6',
        'name': 'Arnaz',
        'image': '/images/arnaz.jpg',
        'price': '18,000',
        'location': 'Palawan',
        'description': 'Enjoy sleek design, cozy spaces, and all the comforts of home. Perfectly located for exploring Palawan, dining, and entertainment.',
        'rating': 5,
    }
]
